"""empty message

Revision ID: 15b4805595e9
Revises: 37112f25da4b
Create Date: 2026-07-29 18:41:28.875770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15b4805595e9'
down_revision = '37112f25da4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_key',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('api_key', sa.String(length=255), server_default=sa.text("''::character varying"), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('remark', sa.String(length=255), server_default=sa.text("''::character varying"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_api_key_id')
    )
    with op.batch_alter_table('api_key', schema=None) as batch_op:
        batch_op.create_index('api_key_account_id_idx', ['account_id'], unique=False)
        batch_op.create_index('api_key_api_key_idx', ['api_key'], unique=False)

    op.create_table('end_user',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('app_id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_end_user_id')
    )
    with op.batch_alter_table('end_user', schema=None) as batch_op:
        batch_op.create_index('end_user_app_id_idx', ['app_id'], unique=False)
        batch_op.create_index('end_user_tenant_id_idx', ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('end_user', schema=None) as batch_op:
        batch_op.drop_index('end_user_tenant_id_idx')
        batch_op.drop_index('end_user_app_id_idx')

    op.drop_table('end_user')
    with op.batch_alter_table('api_key', schema=None) as batch_op:
        batch_op.drop_index('api_key_api_key_idx')
        batch_op.drop_index('api_key_account_id_idx')

    op.drop_table('api_key')
    # ### end Alembic commands ###
