"""empty message

Revision ID: 9eab13b327db
Revises: 17a7278a82b0
Create Date: 2026-07-12 00:10:26.293804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9eab13b327db'
down_revision = '01defc189900'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_dataset_join',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('app_id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_app_dataset_join_id')
    )
    with op.batch_alter_table('app_dataset_join', schema=None) as batch_op:
        batch_op.create_index('app_dataset_join_app_id_dataset_id_idx', ['app_id', 'dataset_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_dataset_join', schema=None) as batch_op:
        batch_op.drop_index('app_dataset_join_app_id_dataset_id_idx')

    op.drop_table('app_dataset_join')
    # ### end Alembic commands ###
