server {
    listen 80;
    server_name www.zhixuspace.cn zhixuspace.cn;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name www.zhixuspace.cn zhixuspace.cn;

    location /api/ {
        proxy_pass http://llmops-api:5001;
        rewrite ^/api/(.*)$ /$1 break;
        include proxy.conf;
    }

    location / {
        proxy_pass http://llmops-ui:3000;
        include proxy.conf;
    }

    ssl_certificate /etc/ssl/zhixuspace.cn_bundle.crt;
    ssl_certificate_key /etc/ssl/zhixuspace.cn.key;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;
}
