server {
    listen 80;
    server_name _;
    # 灏?api鐨勮姹備唬鐞嗗埌5001绔彛涓?llmops-api鏈嶅姟)
    location /api/ {
        proxy_pass http://llmops-api:5001;
        # 淇璺緞锛岄伩鍏?api鍚庨潰鐨勮矾寰勪涪澶?
        rewrite ^/api/(.*)$ /$1 break;
        include proxy.conf;
    }
    # 灏?鐨勮姹傝浆鍙戝埌3000绔彛涓?llmops-ui鏈嶅姟)
    location / {
        proxy_pass http://llmops-ui:3000;
        include proxy.conf;
    }
}
# server {
#     listen 80;
#     server_name _;
#     return 301 https://$host$request_uri;
# }

# server {
#     listen 443 ssl;
#     server_name llmops.shortvar.com;
#
#     # 灏?api鐨勮姹備唬鐞嗗埌5001绔彛涓?llmops-api鏈嶅姟)
#     location /api/ {
#         proxy_pass http://llmops-api:5001;
#         # 淇璺緞锛岄伩鍏?api鍚庨潰鐨勮矾寰勪涪澶?
#         rewrite ^/api/(.*)$ /$1 break;
#         include proxy.conf;
#     }
#
#     # 灏?鐨勮姹傝浆鍙戝埌3000绔彛涓?llmops-ui鏈嶅姟)
#     location / {
#         proxy_pass http://llmops-ui:3000;
#         include proxy.conf;
#     }
#
#     # 寮€鍚疕ttps鏀寔
#     ssl_certificate ./../ssl/llmops.shortvar.com.crt;
#     ssl_certificate_key ./../ssl/llmops.shortvar.com.key;
#     ssl_protocols TLSv1.1 TLSv1.2 TLSv1.3;
#     ssl_prefer_server_ciphers on;
#     ssl_session_cache shared:SSL:10m;
#     ssl_session_timeout 10m;
# }

